# Generated by Django 4.1.2 on 2022-12-31 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kitab', models.CharField(max_length=100)),
                ('bab', models.CharField(max_length=50)),
                ('fasol', models.CharField(max_length=50)),
                ('penjelasan', models.IntegerField(null=True)),
            ],
        ),
    ]
